import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Box, ChakraProvider } from '@chakra-ui/react';
import Header from './components/Header';
const inter = Inter({ subsets: ['latin'] });
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'react-confirm-alert/src/react-confirm-alert.css';
import Footer from './components/Footer';
import { InmoProvider } from './context/InmoContext';
import { FaWhatsapp } from 'react-icons/fa';
import { useState } from 'react';
import WhatsAppModal from './components/WhatsAppModal';
import WhatsAppButton from './components/WhatsAppButton';

export const metadata: Metadata = {
  title: 'Inmobiliaria Santamarina & Asoc.',
  description: 'Generated by create next app',
  icons: ['/favicon.ico']
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <InmoProvider>
          <ChakraProvider>
            <ToastContainer />
            <div
              style={{
                minHeight: '100vh',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'space-between'
              }}
            >
              <div>
                <Header className='desktop-header' />
                <Header className='mobile-header' />
                {children}
                <WhatsAppModal />
              </div>
              <Footer />
            </div>
            <WhatsAppButton />
          </ChakraProvider>
        </InmoProvider>
      </body>
    </html>
  );
}
