export const defaultProperty = {
  _id: 'last',
  title: 'last',
  location: 'last',
  stories: 0,
  pool: false,
  garage: 0,
  isPrivate: false,
  antiquity: 0,
  internet: false,
  ac: false,
  heat: false,
  gas: false,
  more: 'last',
  category: 'last',
  operationType: 'last',
  rooms: 'last',
  showPrice: false,
  coveredMeters: 0,
  totalMeters: 0,
  price: 0,
  images: ['/img-placeholder.jpg'],
  bedrooms: 0,
  bathrooms: 0,
  available: false,
  interestedUsers: []
};
